steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["-m", "rsync", "-r", "-c", "-d", "-x",".*yaml$",".", "gs://www.ksmadhavan.in"]
# Run 
# $> gsutil -m iam ch -r allUsers:legacyObjectReader gs://www.ksmadhavan.in
# $> gsutil -m iam ch allUsers:objectViewer gs://www.ksmadhavan.in